name: CI with Email Step

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 24f3000363@ds.study.iitm.ac.in - Run tests
      run: |
        echo "This step contains my email address in the name"
        echo "Current directory: $(pwd)"
        echo "Listing files:"
        ls -la
        
    - name: Build completion
      run: echo "Workflow completed successfully!"
